language: node_js
node_js:
- 12.6.0
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: zinovik@gmail.com
  on:
    repo: zinovik/node-router-telegram
    branch: master
  skip_cleanup: true
  api_key:
    secure: HeAic1zdjyoCRgLUTiy4B4mGk3G/HELfeaI3frQ8oIjxpV5ANACdL/vYl4Mb/DHfSWbik8sO01jRTxjWvxp8E54OEybjy1WdBOtL8uDUhYiAFKVxAPZlayLVX+iv5HI7C7g7NLzM8s765J9D88UBf42eQ00xWA7Q9Ol53YirqHY16ndHNEfLnf3mItrwLVtKRMA7KzLHiM7flEq/sCQmFzVgE2UyUBKMyMcENuwcC0V8bZhovN9iZWLqRwbyXNAWtbv5BggntXGZTpPNWD7O4ckzR+RUiqpUtcdnn+E38h6o31tgCmBKHV2ujrRSVfUoM4IIQHQ6+hs/i3J5OvRiVbflCMnGyiXr1qd7Zy/N46Es5RUXhGyhoinf71YIUq1mpm1xiskIx9af4vBs0lnKZ2MHDENc7ag3sj9xxLBKZNn2aP7QOhHJmmZaN+oeQB3d6DCe+GcQZbQZmUSz6uC8M9HaDrWeY4WCopqUqDTS/zct5zeVNU3uHRZXB83F/UVdX8hfRTd7PCB10U5TuZP9a8sg9U5EJNTFi/KIeAIZv8XUguIRt9avs+dQfvWt7lHEdX7DATycoERK4JsNBRo0GM7jKEEG/I6pfwoixFH+4iUqF7pj4/GuRTiNxThU0kkYqQe2QdqGEGWrtgnW5GllH/glcXSTu/b4GYZ65C3tCoA=
