language: node_js
node_js:
  - 12.6.0
script:
  - npm run lint
  - npm run test
deploy:
  provider: npm
  email: zinovik@gmail.com
  on:
    repo: zinovik/node-router-telegram
    branch: master
  skip_cleanup: true
  api_key:
    secure: bBn21iRqjACLj9wq8rdDDjutTLiU+euulqibUDGgIv5y5dKjadCZUFH5jkd5RbiwsD0DCFWz/v3yAAssZ68CG78ofwF1JsB9VQuwSHk/iF61xIYUSSUZOO8wlkIC+Lhi6/Cpj7+b+jL/A5YuUKgYzlp4qrFFkltOwTZCYI105IBVeb7PtXyXr9VztvGOqsD1GKRfGcBwwficUBWsdS16VqyNHJCI6TU2wUi83K6x7MEbWyTBcSBrSNIeybAQcPNGAFtHyALZ1PTj5wy5x6bYRJRCzL/ZD10h4ArnqQNH2uejbfr5pVp2TGi+iNTtix+5PKJb4/gTstYP339XotMP0kJbfwuoigU8LEDbjKkaWaqQvKUPsdTRaVdJJdpxW8bDvrouECCAbTObzeVT00Djf2pCEY3bNhrwmWTXnu1z2gqmUPhZJWwOz+g05k1i5OFR98SG7bUeaasgtDiJJFdYyYtPsbm41h0BsfixWbhizCy5D7M2CThcfKAApM9BAPxAUxwDz5wpxtpfXmWieknU8pd0NLPMr8NzAEmK25KIV0yO0lPSfXvyO0PWhBe48KlISzZ0M6ztFQpasoKG8uMXSmn6BXP8Fg87PUCYAIfyX9yF7RfAd8oSfmsy2K3YKRQPS34etPWzHyFEzWywC24NC/Itk3k/sCDLHw+CLmVYEKo=
