language: node_js
node_js:
- '12.6.0'
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: zinovik@gmail.com
  on:
    repo: zinovik/node-router-telegram
    branch: master
  skip_cleanup: true
  api_key:
    secure: Ad3oNFK16EVxBn38xXX0r0uBs0VN+CnPxKcelJxoPAWC7admxaLiALkXacXRfQK8tsRUsnxTNQEV5N/KwxpH4Dy8B1VOrwp+bYelnb+dKZMCLRl5/+eRHF6gE+YSVnHi02VRx3HPrAcNRh+q218hitdtUO5s9JOqbeOyfih+KumEFrsbdrsLBFWmAU2WzKoqAhFL8T+Dp1PkNmTfkCvd3W0K30BhLSHoPIKr3PgXp9kTdRx/bsSPgVaxmh7ScUjrHqB/c0CboFbCukgIuzi2FqirE4wqvAcUbZYk0gg6Tte7wbdeMQyyN0WkXqAShrjvPvWhiwBDRM62M0NNJVqVaPEYkRZ1sQ3dAZfIBEd2p3DOO3fE/4/mCNqqjJ11fsCZRLXB4EVzZ7eSPFXUsiS5xGOe0GRqLcK8tumL7Wr5lThvr3OzbqU2emWdmig3DtXN6+Tr7xDLsUFgMX3WUrkYSnGjEUzXeCXp68GE/AvQEmSO8uuy6dbkD/jNWAi0ojb4BTfw5a6eQDEppuBHFMA3botf3Cu5uJEveIMfOxkd39EPzxrAX0yVQ4+fGEdI+k5r+dp2232fRbLp15U0e1JzAz0g3UtB6xZvIy1EuflHT7E9q2u8xCSemoQWap/tYmt4xihtobaN5Iecbh2+5vtEHr0X0t8n11sNjHhEbBrZ2gc=
