language: node_js
node_js:
- 12.6.0
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: zinovik@gmail.com
  on:
    repo: zinovik/node-router-telegram
    branch: master
  skip_cleanup: true
  api_key: $NPM_TOKEN
